version: 2
jobs:
    build_project:
        working_directory: ~/angular-design-patterns
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: |
                    yarn install --frozen-lockfile
            - save_cache:
                name: Save Cache
                paths:
                    - ~/.cache
                    - node_modules
                key: v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Prettier Check
                command: |
                    yarn prettier:check
            - run:
                name: Lint
                command: |
                    yarn lint
            - run:
                name: Unit Tests
                command: |
                    yarn test --no-watch --code-coverage
            - run:
                name: Build Project
                command: |
                    yarn build
            # Save the coverage folder for codecov report upload.
            - persist_to_workspace:
                root: .
                paths:
                    - coverage
    coverage_report:
        working_directory: ~/angular-design-patterns
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './coverage/lcov.info'
                token: 4cb4f10a-b3f7-4e5e-b4ba-6e5d5d272eb7
    cypress_tests:
        working_directory: ~/angular-design-patterns
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: |
                    yarn install --frozen-lockfile
            - save_cache:
                name: Save Cache
                paths:
                    - ~/.cache
                    - node_modules
                key: v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Cypress E2E Tests
                command: |
                    yarn cytest
            - store_artifacts:
                path: cypress/screenshots

workflows:
    version: 2
    angular_design_patterns:
        jobs:
            - build_project
            - coverage_report:
                requires:
                    - build_project
                # filters:
                #     branches:
                #         only:
                #             - master
            - cypress_tests:
                    requires:
                        - build_project
                    filters:
                        branches:
                            only:
                                - master
                                - dev
